backend:
  name: git-gateway
  repo: bartdw/static # Path to Github repository
  branch: master # Branch to update

media_folder: "images" # Media files will be stored in the repo under images
public_folder: "/images" # The src attribute for uploaded media will begin with /images


collections:
  - name: "activiteiten" # Used in routes, e.g. /admin/collections/blog
    label: "Activiteiten" # Used in the UI
    folder: "_activiteiten" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tijdstip", name: "tijdstip", widget: "datetime", format: "DD-MM-YYYY HH:mm"}
      - {label: "Plaats", name: "plaats", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "teksten" # Used in routes, e.g. /admin/collections/blog
    label: "Teksten" # Used in the UI
    folder: "_teksten" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
